### ISSUE TITLE
Where to configure

### ISSUE THREAD

**Issue by thoefkens** [KozhanovDmytro/localstack-intellij-idea-plugin-public#1] opened 2024-03-18 19:47 UTC
Hi Dmytro,

Where can I configure the Localstack settings?
I have it running at the default address / port - with awslocal I can e.g. list running queues, but in the plugin I do not see them.

Btw my region is an eu- one.
<img width="386" alt="image" src="https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/97980582/c6a700e6-2757-45d5-95d7-3cbad86201c0">

Thanks
Thomas

**Comment by KozhanovDmytro** [comment] 2024-03-18 19:55
Hi Thomas,

Please follow these steps to configure the URL address, ports, etc.:

1. Go to `File` -> `Settings`,
2. On the left side, select `Tools` and then choose `LocalStack Plugin Settings`.
3. Here, you can change the URL, Region, Access Keys, Secret Keys, and other configurations.
4. Please restart your IDE and enjoy :)

![image](https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/33006436/c21a675d-f889-4f92-b03d-15f1db761e69)

Let me know if you have any questions.

Cheers,
Dmytro

**Comment by thoefkens** [comment] 2024-03-18 19:59
Hi Dmytro,

Great, thanks for the quick pointer!

1. Would be great if you add that to the docs / readme ;).
2. Still does not work though, but perhaps I missed something again:
<img width="406" alt="image" src="https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/97980582/c183ce6e-bed3-4ae5-8140-f7cbc815fc92">

An AWS SQS list queues command works, with my profile pointing to 
<img width="299" alt="image" src="https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/97980582/d9028b3c-2cf4-4884-8153-772dabb384f2">

Thanks
Thomas

**Comment by KozhanovDmytro** [comment] 2024-03-18 20:03
Certainly! Please restart your IDE. This step is necessary for the plugin to pick up and apply the new configs.

**Comment by thoefkens** [comment] 2024-03-18 20:07
Yes, I did do that.. but now the error / warning appears saying sqs.eu-central-1.localhost.localstack.cloud is unreachable.
Please note I just have Localstack installed on my Mac, up and running - no Localstack cloud involved.

**Comment by thoefkens** [comment] 2024-03-19 08:26
@KozhanovDmytro Should I create a hosts entry to workaround this problem?

**Comment by KozhanovDmytro** [comment] 2024-03-19 08:29
I don't think so, I'll check this issue later and let you know

**Comment by KozhanovDmytro** [comment] 2024-03-19 09:09
@thoefkens, could you please share the plugin settings? 

and just want to clarify.. you mention this aws profile works for you, am I correct?
![image](https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/33006436/9471e24f-0a70-4a82-8203-2d5edca10890)
did you try just putting `http://localhost:4566` as URL address?

**Comment by thoefkens** [comment] 2024-03-19 09:49
Yes, exactly. I can also fetch queues etc. using --profile local stack.

These are the plugin settings 
![image](https://github.com/KozhanovDmytro/localstack-intellij-idea-plugin-public/assets/97980582/04ef9e05-f177-4f20-932c-5201a0df8613)

I did not specify localstack.cloud anywhere...

**Comment by thoefkens** [comment] 2024-03-21 09:16
@KozhanovDmytro Should I wait for a small fix, perhaps?

**Comment by KozhanovDmytro** [comment] 2024-03-21 09:47
@thoefkens still not sure what cause that issue. 

I tried to reproduce with `3.1.1` but it works fine on my Windows machine. 
I guess that the problem may be that Localstack is doing a redirect from `localhost` to `sqs.eu-central-1.localhost.localstack.cloud`. Looks weird. 

This is my Localstack info: 
```
LocalStack version: 3.1.1.dev
LocalStack Docker container id: d3fd89800c52
LocalStack build date: 2024-02-27
LocalStack build git hash: e03147cd4
```

Could you please share your LocalStack version?

**Comment by thoefkens** [comment] 2024-03-21 14:37
Hi @KozhanovDmytro 

My version is 3.2.0
I am using LocalStack on macOS Sonoma.

Thank you 
Thomas

**Comment by KozhanovDmytro** [comment] 2024-03-24 19:06
Hi @thoefkens. 

Thank you for the additional information. Here are some updates regarding the issue:
1. I've tested the plugin on macOS with version `3.2.1.dev`, and everything works as expected. The details are as follows:
```
LocalStack version: 3.2.1.dev
LocalStack build date: 2024-03-22
LocalStack build git hash: 185ec334f`
```
2. I've also uploaded a new version, `2024.1.5`, with a potential fix and added logging. This build will be available for download after JetBrains completes its usual review process, so it should be available to you within the next two business days. 
3. Additionally, I wanted to clarify that the plugin does not generate domains such as `sqs.eu-central-1.localhost.localstack.cloud` internally. Looks like this behavior is coming from LocalStack itself. 

It seems more likely that the issue lies or with your local setup or possibly a bug in LocalStack. 
Could you please try updating LocalStack on your local machine to version `3.2.1`, which is available now?

Thanks,
Dmytro

**Comment by thoefkens** [comment] 2024-04-05 07:56
Hi Dmytro,


I found out this is related to running LocalStack on MacOS.
One needs to add 127.0.0.1 as a DNS server, so that localstack.cloud<http://localstack.cloud/> addresses can be resolved, These are the default endpoints LocalStack / LocalStack Desktop work with.
After resolving that networking issue, the plugin also worked fine.

Thanks for your support!
Just thought it would be good to let you know in case some other (plugin) users stumble into this issue in the future.

Best regards,
Thomas


Thomas Hoefkens
***@***.******@***.***>
Tel. +49 173 575 40 10


On Sun, Mar 24, 2024 at 8:06 PM, KozhanovDmytro ***@***.******@***.***>> wrote:

Hi @thoefkens<https://github.com/thoefkens>.

Thank you for the additional information. Here are some updates regarding the issue:

  1.  I've tested the plugin on macOS with version 3.2.1.dev<http://3.2.1.dev/>, and everything works as expected. The details are as follows:

LocalStack version: 3.2.1.dev<http://3.2.1.dev/>
LocalStack build date: 2024-03-22
LocalStack build git hash: 185ec334f`


  1.  I've also uploaded a new version, 2024.1.5, with a potential fix and added logging. This build will be available for download after JetBrains completes its usual review process, so it should be available to you within the next two business days.
  2.  Additionally, I wanted to clarify that the plugin does not generate domains such as sqs.eu-central-1.localhost.localstack.cloud<http://sqs.eu-central-1.localhost.localstack.cloud/> internally. Looks like this behavior is coming from LocalStack itself.

It seems more likely that the issue lies or with your local setup or possibly a bug in LocalStack.
Could you please try updating LocalStack on your local machine to version 3.2.1, which is available now?

Thanks,
Dmytro

**Comment by KozhanovDmytro** [comment] 2024-04-06 17:28
Hi Thomas

Thank you for your effort for resolving this issue! Will close this ticket then.
I've updated the documentation and added your case in troubleshooting section.

If you have any additional comments, improvements or even feature you would like to see in the plugin, please feel free to contact me kozhanov.dmytro@gmail.com or leave a feedback in the plugin `Tools` -> `LocalStack` -> `Feedback`.

Have a nice weekend!

Best regards,
Dmytro

**Closed as completed by KozhanovDmytro** 2024-04-06 17:28 UTC
